-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria text COLLATE pg_catalog."default" NOT NULL,
    codigo_categoria text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id),
    CONSTRAINT categoria_codigo_categoria_key UNIQUE (codigo_categoria)
);

CREATE TABLE IF NOT EXISTS public.embeddings
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_publicaciones bigint NOT NULL,
    contenido text COLLATE pg_catalog."default" NOT NULL,
    contenido_emb_dense vector NOT NULL,
    contenido_emb_sparse hstore NOT NULL,
    resumen text COLLATE pg_catalog."default" NOT NULL,
    resumen_emb_dense vector NOT NULL,
    resumen_emb_sparse hstore NOT NULL,
    CONSTRAINT embeddings_pkey PRIMARY KEY (id),
    CONSTRAINT embeddings_id_publicaciones_key UNIQUE (id_publicaciones)
);

CREATE TABLE IF NOT EXISTS public.publicaciones
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    titulo text COLLATE pg_catalog."default" NOT NULL,
    autores text COLLATE pg_catalog."default" NOT NULL,
    fecha_publicacion date NOT NULL,
    categoria_principal bigint NOT NULL,
    categorias_lista text COLLATE pg_catalog."default" NOT NULL,
    url_pdf text COLLATE pg_catalog."default" NOT NULL,
    identificador_arxiv text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT publicaciones_pkey PRIMARY KEY (id),
    CONSTRAINT publicaciones_identificador_arxiv_key UNIQUE (identificador_arxiv)
);

ALTER TABLE IF EXISTS public.embeddings
    ADD CONSTRAINT fk_id_publicaciones FOREIGN KEY (id_publicaciones)
    REFERENCES public.publicaciones (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS embeddings_id_publicaciones_key
    ON public.embeddings(id_publicaciones);


ALTER TABLE IF EXISTS public.publicaciones
    ADD CONSTRAINT fk_categoria_principal FOREIGN KEY (categoria_principal)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;